# Generated by Django 5.1.3 on 2024-12-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_localizeaccommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField(default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accommodation')),
            ],
        ),
    ]
