# Generated by Django 5.1.3 on 2024-12-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_localizeaccommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
