# Generated by Django 5.1.3 on 2024-12-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_accommodation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_abbr',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
