

services:
  web:
    build: .
    container_name: inventory_management_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=knm
      - POSTGRES_PASSWORD=knm123
    depends_on:
      - db
    networks:
      - inventoryManagement_network

  db:
    image: postgis/postgis:15-3.3
    container_name: inventory_management_db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: knm
      POSTGRES_PASSWORD: knm123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=200'

    networks:
      - inventoryManagement_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - inventoryManagement_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  inventoryManagement_network:
    driver: bridge
